### ISSUE TITLE
Insert or Update

### ISSUE THREAD

**Issue by StephanKrauss** [FaaPz/PDO#72] opened 2017-03-10 13:44 UTC
Hello,

I'm looking for a way to write a combined update.
Example:

INSERT INTO table (a,b,c) VALUES (1,2,3),(4,5,6)
  ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);

Your sincerly

Stephan

**Comment by shaq147** [comment] 2017-06-05 21:28
@StephanKrauss  Hi, I've implemented this functionality. You've just gotta add a few new functions to the InsertStatement.php file. See https://github.com/FaaPz/Slim-PDO/issues/86

**Comment by kwhat** [comment] 2019-09-20 22:23
This is a duplicate of #86

**Closed as completed by kwhat** 2019-09-20 22:23 UTC
Labels: duplicate, enhancement
