### ISSUE TITLE
Update table with existing value?

### ISSUE THREAD

**Issue by bduman** [FaaPz/PDO#63] opened 2016-10-29 15:14 UTC
I looked set method of Slim\PDO\Statement\UpdateStatement class and it doesnt provide self column aritmetic operations such as `count=count+?`, `count=count-?` etc.  It could be flexible implement of this method with 2d arrays.

Thnx for repo.

**Comment by You2s** [comment] 2018-02-11 22:50
I confirm, this feature would be very useful

**Comment by kwhat** [comment] 2019-06-28 22:22
This is a duplicate of #108

**Closed as completed** 2019-06-28 22:22 UTC
Labels: duplicate
